### ISSUE TITLE
Cinny cant be installed on mydomain.org/cinny

### ISSUE THREAD

**Issue by KazeroG** [YunoHost-Apps/cinny_ynh#11]
### Describe the bug
When you want to install the app the URL have to be as subdomain : `cinny.mydomain.org` not sub link url `mydomain.org/cinny`

Check the Disclaimers / important information
```
The app only supports being installed at the root of a domain. This is an upstream limitation.

ok: mydomain.org/
ok: cinny.mydomain.org/
NOT ok: mydomain.org/cinny
There's no LDAP support (and never will be).

Cinny only is a client, you need to have an account on a server already (see the Synapse Yunohost app)
```

![Inkedscreenshot-panel allowebs com-2021 12 08-13_46_27_LI](https://user-images.githubusercontent.com/17680194/145266336-4dc5a4fe-a8ff-42c7-8004-fb893b203903.jpg)

### Context

- Hardware: `VPS online`
- YunoHost version: `4.3.4.1`

**Comment by KazeroG** [comment]
Error misunderstanding, sorry about that !

**Comment by ericgaspar** [comment]
@KazeroG I think you are right, we shouldn't have the path option during install as the only choice is `/`

**Comment by Salamandar** [comment]
I'm sorry, I was really sure I merged the fix for that. This was an issue upstream, fixed some time ago.

**Comment by olberger** [comment]
It seems this may have changed between v3.2 (which allowed subpath) and 4.2.3, currently available, so back to the starting point, IIUC
